# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-release

addons:
  apt:
    packages:
      - libxml2-dev
      - bowtie2
      - samtools

# Don't build vignettes
before_install:
  - rm -rf vignettes
  - curl -L https://github.com/lh3/minimap2/releases/download/v2.13/minimap2-2.13_x64-linux.tar.bz2 | tar -jxvf -
  - cp ./minimap2-2.13_x64-linux/minimap2 /usr/bin/minimap2

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
