# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-release
r_build_args: "--no-build-vignettes"
addons:
  apt:
    packages:
      - libxml2-dev
      - bowtie2
      - samtools

after_success:
- Rscript -e 'covr::codecov()'
