# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-release

env:
  - CXX=g++-5

addons:
  apt:
    packages:
      - libxml2-dev
      - samtools
      - cmake
      - gcc-5
      - g++-5

# Don't build vignettes
before_install:
  - rm -rf vignettes
  - curl -L https://github.com/lh3/minimap2/releases/download/v2.13/minimap2-2.13_x64-linux.tar.bz2 | tar -jxvf -
  - sudo cp ./minimap2-2.13_x64-linux/minimap2 /usr/bin/ && rm -rf ./minimap2-*
  - git clone --recursive https://github.com/seqan/slimm
  - (cd slimm && mkdir build && cd build && cmake .. && make && cp bin/slimm /usr/bin/)
  - rm -rf slimm

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
