# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-release

env:
  - CXX=g++-9

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libxml2-dev
      - cmake
      - gcc-9
      - g++-9
      - autoconf
      - automake
      - perl
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libcurl4-gnutls-dev
      - libssl-dev
      - libncurses5-dev

r_packages:
  - vegan

r_github_packages:
  - bryandmartin/corncob

# Don't build vignettes
before_install:
  - rm -rf vignettes
  - curl -L https://github.com/lh3/minimap2/releases/download/v2.13/minimap2-2.13_x64-linux.tar.bz2 | tar -jxf -
  - sudo cp ./minimap2-2.13_x64-linux/minimap2 /usr/bin/ && rm -rf ./minimap2-*
  - git clone --recursive https://github.com/seqan/slimm
  - (cd slimm && mkdir build && cd build && cmake .. && make && sudo cp bin/slimm /usr/bin/)
  - rm -rf slimm
  - curl -L https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2 | tar -jxf -
  - (cd samtools-1.10 && autoheader && autoconf -Wno-syntax && ./configure && make && sudo cp samtools /usr/bin/)
  - rm -rf samtools
  - echo "options(Ncpus = 4)" >> $R_PROFILE
  - cat $R_PROFILE

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
