resources:
  repositories:
    - repository: r-azure-pipelines
      type: github
      name: r-lib/r-azure-pipelines
      endpoint: Gibbons-Lab

jobs:
  - template: azure-tidyverse.yml@r-azure-pipelines
