jobs:
  - job: 'Linux'
    variables:
      CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
      TZ: UTC
      CI: true
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        R-3.6:
          containerImage: rstudio/r-base:3.6-xenial
    container: $[ variables['containerImage'] ]
    steps:
      - bash: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libssl-dev git bzip2 \
            cmake autoconf automake make gcc perl zlib1g-dev libbz2-dev \
            liblzma-dev libcurl4-gnutls-dev libssl-dev libncurses5-dev
        displayName: "Install System Dependencies"
      - bash: |
          echo 'options(repos = "$(CRAN)", Ncpus = 2, crayon.enabled = TRUE)' > ~/.Rprofile
          mkdir -p $(R_LIBS_USER)
        displayName: "Setting up R library"
      - bash: |
          rm -rf vignettes
          curl -L https://github.com/lh3/minimap2/releases/download/v2.13/minimap2-2.13_x64-linux.tar.bz2 | tar -jxf -
          sudo cp ./minimap2-2.13_x64-linux/minimap2 /usr/bin/ && rm -rf ./minimap2-*
          git clone --recursive https://github.com/seqan/slimm
          (cd slimm && mkdir build && cd build && cmake .. && make && sudo cp bin/slimm /usr/bin/)
          rm -rf slimm
          curl -L https://github.com/samtools/samtools/releases/download/1.10/samtools-1.10.tar.bz2 | tar -jxf -
          (cd samtools-1.10 && autoheader && autoconf -Wno-syntax && ./configure && make && sudo cp samtools /usr/bin/)
          rm -rf samtools-1.10
        displayName: "Install tools"
      - bash: |
          Rscript -e "install.packages(c('devtools', 'rcmdcheck', 'BiocManager', 'rmarkdown'))"
          Rscript -e "devtools::install_github('bryandmartin/corncob')"
          Rscript -e "setRepositories(ind=1:4); devtools::install_deps(dependencies = TRUE)"
        displayName: "Install dependencies"
      - bash: |
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"
        displayName: 'Check package'
      - task: PublishTestResults@1
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'check/*.Rcheck/tests/test-*.xml'
          testRunTitle: $(Agent.JobName)
        condition: succeededOrFailed()
      - publish: check
        artifact: $(Build.BuildNumber)-$(Agent.JobName)-check_results
        condition: succeededOrFailed()
