jobs:
  - job: 'Linux'
    variables:
      CRAN: 'https://demo.rstudiopm.com/all/__linux__/xenial/latest'
      R_LIBS_USER: '$(Agent.BuildDirectory)/R/library'
      TZ: UTC
      CI: true
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        R-3.6:
          containerImage: rocker/r-base:latest
    container: $[ variables['containerImage'] ]
    steps:
      - bash: apt-get update && apt-get install -y libxml2-dev libssl-dev
        displayName: "Install System Dependencies"
      - bash: |
          echo 'options(Ncpus = 2, crayon.enabled = TRUE)' > ~/.Rprofile
          mkdir -p $(R_LIBS_USER)
        displayName: "Setting up R library"
      - bash: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'BiocManager'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
          - bash: |
          Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"
        displayName: 'Check package'
      - task: PublishTestResults@1
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'check/*.Rcheck/tests/test-*.xml'
          testRunTitle: $(Agent.JobName)
        condition: succeededOrFailed()
      - publish: check
        artifact: $(Build.BuildNumber)-$(Agent.JobName)-check_results
        condition: succeededOrFailed()
